FROM savonet/liquidsoap:rolling-release-v2.2.x

USER root

RUN apt-get -y update

RUN apt-get -y install make ffmpeg imagemagick

USER liquidsoap

RUN mkdir /tmp/liq

ADD liq /tmp/liq

WORKDIR /tmp/liq

USER root

RUN chmod a+w to-play

RUN export LIQLIB=`liquidsoap --check "print(configure.libdir)"` && \
    echo "let output.graphics = output.dummy" >> $LIQLIB/io.liq && \
    echo "let input.v4l2 = blank" >> $LIBLIQ/ffmpeg.liq

USER liquidsoap

RUN make files

RUN make test
