FROM savonet/liquidsoap:main

USER root

RUN apt-get -y install make ffmpeg

USER liquidsoap

RUN mkdir /tmp/liq

ADD liq /tmp/liq

WORKDIR /tmp/liq

USER root

RUN chmod a+w to-play

USER liquidsoap

RUN make files

RUN make test
