name: CI
on: [push]
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install packages
      run: |
        sudo apt-get -y update
        sudo apt-get -y install pandoc texlive texlive-fonts-extra imagemagick poppler-utils pdf2svg ocaml-nox ocaml-findlib libyojson-ocaml-dev ocaml-dune
    - name: Build pandoc filters
      run: |
        git clone https://github.com/smimram/ocaml-pandoc
        cd ocaml-pandoc
        dune build @install
        sudo dune install --prefix /usr/local -p pandoc-crossref
        sudo dune install --prefix /usr/local -p pandoc-include
        sudo dune install --prefix /usr/local -p pandoc-replace
        sudo dune install --prefix /usr/local -p pandoc-pdf2png
    - name: Build book
      run: |
        make
        pdflatex book.tex
        pdflatex book.tex
    - name: Build cover
      run: |
        make -C cover
        cp cover/cover.pdf .
        cp cover/cover-ebook.jpg .
    - name: Build ebook
      run: make book.epub
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: book
        path: |
          book.pdf
          cover.pdf
          book.epub
          cover-ebook.jpg
    - name: Generate pages
      run: |
        make site
        cp book.pdf site/public
        cp book.epub site/public
    - name: Deploy pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site/public
    - name: Test scripts
      run: docker build . -f .github/docker/Dockerfile.build
