name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install packages
      run: sudo apt-get install pandoc texlive ocaml-nox ocaml-findlib libyojson-ocaml-dev
    - name: Build
      run: make
