name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install packages
      run: sudo apt-get install pandoc pandoc-citeproc texlive texlive-fonts-extra imagemagick ocaml-nox ocaml-findlib libyojson-ocaml-dev dune
    - name: Enable imagemagick pdf conversion
      run: sudo sed -i 's/<policymap>/<policymap><policy domain="coder" rights="read | write" pattern="PDF" \/>/' /etc/ImageMagick-6/policy.xml
    - name: Build pandoc filters
      run: |
        git clone https://github.com/smimram/ocaml-pandoc
        cd ocaml-pandoc
        dune build @install
        sudo dune install -p pandoc-crossref
        sudo dune install -p pandoc-include
    - name: Build book
      run: |
        make
        pdflatex book.tex
    - name: Build ebook
      run: make ebook.zip
    - name: Build cover
      run: |
        make -C cover
        cp cover/cover.pdf .
        cp cover/cover-ebook.jpg .
    - uses: actions/upload-artifact@v2
      with:
        name: book
        path: |
          book.pdf
          cover.pdf
          ebook.zip
          cover-ebook.jpg
    - name: Test scripts
      run: docker build . -f .github/docker/Dockerfile.build
