name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install packages
      run: sudo apt-get install pandoc pandoc-citeproc texlive texlive-fonts-extra ocaml-nox ocaml-findlib libyojson-ocaml-dev dune
    - name: Build pandoc filters
      run: |
        git clone https://github.com/smimram/ocaml-pandoc
        cd ocaml-pandoc
        dune build @install
        dune install -p pandoc-crossref
        dune install -p pandoc-include
    - name: Build
      run: |
        make
        pdflatex book.tex
    - uses: actions/upload-artifact@v2
      with:
        name: book
        path: book.pdf
    - name: Test scripts
      run: docker build . -f .github/docker/Dockerfile.build
